### ISSUE TITLE
Discussion: How much caching do we need?

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#19]
Given this an a closed beta we're building, what is a reasonable level of caching to expect?

My concern is that unlike other API lookups we would commonly do (Postcode lookups for example) the results are likely to be highly personalised, either because of real-time information (this train is late) or because not everyone is looking for the same point A to point B.

The four options I think we have are:

1. No caching, requests to our website make direct requests to (e.g) TFL endpoints in real time (Slowest end user experience, but by far the least amount of work)
2. Time-based caching, we store the results of a lookup in our own database for a certain amount of time, new requests look to our database first before going over a network (easiest to implement, will help with repeated refreshes)
3. User-based caching, we cache based on user requests and allow them to force a refresh of the cache
4. Pre-emptive caching, we perform lookups ahead of time and store them so when a user does the lookup we have the data locally (I don't think this makes sense in our context)

**Comment by francosta** [comment]
Not having had any experience with this, I would say that the best solution really will depend on the actual user experience designed.

That said, I agree on some of the assumptions you set out and add:
- requests will likely be quite personalised (not only points of origin and destination but also accessibility needs, time of departure/arrival, etc.). All requests, having any minor difference, will potentially get different responses;
- responses from the TfL API for the same request will also get different responses at different times;
- I assume the same user will likely make similar requests in terms of point of origin and destination;

Given these assumptions and what we already know of the app, I agree that option 4 doesn't make much sense.

If we have a product that is focused on real time travel I'd say that no caching should be the way to go (option 1).
If we have a product that is focused on the user getting a planned journey (possibly centred around a printable step-by-step guide), then I would say that options 2 or 3 could be considered. I'm not sure which one would make more sense but thinking about the last assumption, probably option 3?

**Comment by mathewtrivett** [comment]
We experimented with caching a bit today.

In our experimentation we were effectively exploring Option 2. We cached the response we got from TfL so we could:

- reuse the data across views
- improve performance (loading data from the cache rather than an API request)
- avoid spamming the TfL API.

However, it also raised a wider set of questions around persistence of the data we get back from TfL.

## The challenge

We might **need** to persist the data from TfL some how / somewhere in order to support the features we have planned.

For example, assuming this flow:

1. Select origin
2. Select destination
3. Selection options
4. Query TfL API
**5. Show route options** 
6. Select route
7. Show route
8. (Optionally) show one step at a time

At Step 5, we only have the TfL data in memory.

Without some form of persistence, each step after this we may have to query the API again. The data could change and this might make for a potentially unstable user experience.

I wonder how other travel planner products handle this sort of thing? Might be worth some investigation there.

## Options 

- Database persistance
- Cache persistance
- Session persistance (Not fully explored here)

### Database persistence

@tosbourn it seems like some of the tickets like #41 suggest it might be good to actually persist the TfL response to the database?

This could potentially provide a number of benefits.

#### Pros

- Views could then load route data across requests
- Route selection would then be easier, assuming that we might have a model like `Journey` that `has_many :routes` and `Routes` that `has_many :steps` etc.
- We could potentially explore getting each step in a journey if we wanted to eg. `/routes/:id/steps/:id` we could then create new types of experiences where we just show a step at a time.

#### Cons

- Route data might become stale
- We have to write code to map the JSON data we get back from TfL into our models
- The data model for the results from TfL is quite complex
- If the TfL API changes, our data model might break
- Could end up with a very large database over time

I'm not sure if any of this made sense, a few garbled thoughts at the end of the day.

### Cache persistence

We have a model like `JourneyQuery` to the database and save the TfL response in a cache and load it in views. This is what we tested an implementation for today. Optionally we can provide an expiration

#### Pros

- We can directly save the response from TfL in the cache
- We don't necessarily have to build ActiveRecord models to persist the data
- We can expire data in the cache, re-querying for the latest route. 

#### Cons

- It may be harder to do route selection as it is not clear how to create a restful route for data from the cache. For example, imagine we get back an array of `routes: [route1, route2]` from TfL. Would we use an array index to select the route? For example something like `/journeys/:id/routes/<route1index>` would return `route 1`.
- Deciding on how long we should store data for could be hard.

#### Questions

- How would this work for sharing the link with someone?
- How would this work for emailing it to yourself?
- How would this work for printing?


A lot of thoughts and questions here, apologies. Maybe a conversation might be the best way to figure out what the best route is.

**Comment by mathewtrivett** [comment]
My overall thoughts here are that we should save TfL data to the database but there are a few extra things to consider :)

**Comment by tosbourn** [comment]
Thanks for these incredibly clear thoughts @mathewtrivett!

I think we need some form of persistence to tackle the issues of going between pages if nothing else. Which is why I would suggest storing the results off our side, at the very least then we're dealing with a consistent model and there is a nice separation of concerns.

I imagine the easiest way to "deal" with most of our issues around things becoming stale is that any time "confirm and find routes" is pressed we throw away anything we had and re-seed our trip/steps

**Comment by tosbourn** [comment]
Given our conversation yesterday, and the fact we may need to allow steps to be edited, it feels like persisting them is the way forward.

Closing this ticket for now, since persisting is already in #41 and #60
