### ISSUE TITLE
Discussion: Setup pre-commit hooks to check our code

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#85]
Our continuous integration pipeline checks our code for us post commit. But what if...we could catch continuous integration problems before they hit the pipeline.

Git provides a mechanism to do this with git-hooks. However defining hooks carries a bit of a learning curve and involves writing scripts to do the work for us. Enter [Husky](https://www.npmjs.com/package/husky) an node package that provides a nice wrapper around git tooling.

## Acceptance criteria

- [ ] We run `rubocop` && `brakeman` before we commit our work to flag and fix issues
- [ ] Optionally: we could have it run `rspec` too but this could be annoying if we're working on tests

## Pros

- It saves us time as we don't have to wait until the pipeline fails to learn it was due to a linting error.

## Cons

- There is a risk here that by automating it, we devalue the importance of consciously checking for security vulnerabilities and styling consistency as part of our workflow.

**Comment by mathewtrivett** [comment]
## Pros

- It saves us time as we don't have to wait until the pipeline fails to learn it was due to a linting error.

## Cons

- There is a risk here that by automating it, we devalue the importance of consciously checking for security vulnerabilities and styling consistency as part of our workflow.

**Comment by tosbourn** [comment]
I am all for individual developers installing stuff locally to run pre-commit hooks if they feel it helps their process, however I don't believe this should happen at a project level.

Whilst it is great to catch issues before they are pushed to CI, I feel that pre-commit hooks are in an awkward space. They run _after_ the code has been written, but _before_ that code can go anywhere.

Because they run after code is written, I'm not learning anything that would improve my coding style. I've lost context if the change was in a file I was looking at at the start of my work. In this case an in-line linter such as https://marketplace.visualstudio.com/items?itemName=misogi.ruby-rubocop might give me better and more timely feedback.

Because they run before code can go anywhere, I can't quickly commit Work In Progress code (important when jumping between projects and wanting to put something up to share with someone) this can add to stress levels when trying to move quickly between tasks or projects (something we unfortunately have to do a fair bit).

Because pre-commit hooks need to differ between projects, I need to remember different ways of working.

**Comment by mathewtrivett** [comment]
I am going to close this issue
